# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{librato-services}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Heffner"]
  s.date = %q{2011-11-15}
  s.description = %q{Provides service notifications for alerts}
  s.email = %q{mike@librato.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Procfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "config.ru",
    "config/newrelic.yml",
    "config/unicorn.rb",
    "config/unicorn_new.rb",
    "dot.rvmrc",
    "lib/librato-services.rb",
    "lib/librato-services/app.rb",
    "lib/librato-services/authentication.rb",
    "lib/librato-services/helpers/alert_helpers.rb",
    "lib/librato-services/service.rb",
    "librato-services.gemspec",
    "services/campfire.rb",
    "services/mail.rb",
    "services/pagerduty.rb",
    "services/webhook.rb",
    "test/campfire_test.rb",
    "test/helper.rb",
    "test/mail_test.rb",
    "test/pagerduty_test.rb",
    "test/webhook_test.rb"
  ]
  s.homepage = %q{http://github.com/librato/librato-services}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Provides service notifications for alerts}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.2.6"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.7.5"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 2.3"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<hoptoad_notifier>, [">= 0"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.2"])
      s.add_runtime_dependency(%q<tinder>, ["~> 1.7"])
      s.add_runtime_dependency(%q<unicorn>, [">= 0"])
      s.add_development_dependency(%q<thin>, ["~> 1.2.11"])
      s.add_development_dependency(%q<shotgun>, ["~> 0.8"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, ["~> 1.2.6"])
      s.add_dependency(%q<faraday>, ["~> 0.7.5"])
      s.add_dependency(%q<activesupport>, ["~> 2.3"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<hoptoad_notifier>, [">= 0"])
      s.add_dependency(%q<mail>, ["~> 2.2"])
      s.add_dependency(%q<tinder>, ["~> 1.7"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<thin>, ["~> 1.2.11"])
      s.add_dependency(%q<shotgun>, ["~> 0.8"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, ["~> 1.2.6"])
    s.add_dependency(%q<faraday>, ["~> 0.7.5"])
    s.add_dependency(%q<activesupport>, ["~> 2.3"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<hoptoad_notifier>, [">= 0"])
    s.add_dependency(%q<mail>, ["~> 2.2"])
    s.add_dependency(%q<tinder>, ["~> 1.7"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<thin>, ["~> 1.2.11"])
    s.add_dependency(%q<shotgun>, ["~> 0.8"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

