version: 2
jobs:
  build19:
    docker:
      - image: ruby:1.9.3

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps19-{{ checksum "Gemfile.lock" }}
            - v1-deps19-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-deps19-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake test

  build24:
    docker:
      - image: ruby:2.4.3

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps24-{{ checksum "Gemfile.lock" }}
            - v1-deps24-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-deps24-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake test

workflows:
  version: 2
  build:
    jobs:
      - build19
      - build24
